name: testGit
on: push

jobs:
  myTest:
    runs-on: ubuntu-latest
    steps:
      - name: Instal
        run : make install
      - name: Run linter
        run : make lint
      - name: Run tests
        run : composer exec --verbose phpunit tests
