name: testGit
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: composer exec --verbose phpcs -- --standard=PSR12 src bin tests
      - name: Run tests
        run: composer exec --verbose phpunit tests
